### PR TITLE
Add a table for metadata

### PR DESCRIPTION
**Pull request by rhmdnd**

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]
alternative idea on the metadata:

Why not make the metadata a more general key-value store. Where folks could refer to multiple metadata entries to describe a subject or another entity? This would complicate the implementation a little. you'd need a table for metadata entries with:

* ID: unique reference to the entry
* key
* value

And you'd probably need a table to represent relationships between entities, a subject has x amount of metadata entries. But this would allow us to have more flexible data structures.

That's just one idea...

Otherwise, if we want to have a more targeted metadata definition, this would work.

**Comment by rhmdnd** [comment]
> alternative idea on the metadata:
> 
> Why not make the metadata a more general key-value store. Where folks could refer to multiple metadata entries to describe a subject or another entity? This would complicate the implementation a little. you'd need a table for metadata entries with:
> 
>     * ID: unique reference to the entry
> 
>     * key
> 
>     * value
> 
> 
> And you'd probably need a table to represent relationships between entities, a subject has x amount of metadata entries. But this would allow us to have more flexible data structures.
> 
> That's just one idea...
> 
> Otherwise, if we want to have a more targeted metadata definition, this would work.

That's an interesting idea.

Would the process that ingests data take any additional key-value pairs outside the schema and attempt to insert them in this generic table? If so, would a client be able to fetch that information out using the gRPC API? I may have the cart in front of the horse, but I'm wondering how that will impact the perception of a public facing API. For example, if someone relies on fetch a non-standard key out the metadata, would we ever be able to standardize it as a first-class citizen?

My other thought here is about performance. The generic table would need to have specific data types (e.g., `TEXT`). Should we stuff integers in as text-type and then convert them? In either case, I'm wondering what the performance implications would be if we handled the conversion in go, and/or didn't optimize the types to build specific queries from the application.

**Comment by rhmdnd** [comment]
Rebased to resolve conflicts.

**Comment by JAORMX** [comment]
> That's an interesting idea.
> 
> Would the process that ingests data take any additional key-value pairs outside the schema and attempt to insert them in this generic table? If so, would a client be able to fetch that information out using the gRPC API? I may have the cart in front of the horse, but I'm wondering how that will impact the perception of a public facing API. For example, if someone relies on fetching a non-standard key out the metadata, would we ever be able to standardize it as a first-class citizen?

The GRPC API can still be targetted and target a very specific implementation. The database (or model) doesn't need to be tied to the GRPC API.

> 
> My other thought here is about performance. The generic table would need to have specific data types (e.g., `TEXT`, `VARCHAR`). Should we stuff integers in as text-type and then convert them? In either case, I'm wondering what the performance implications would be if we handled the conversion in go, and/or didn't optimize the schema to build specific queries from the application

Definitely, this would have some performance impact. It really depends on the data ingestion rate. Maybe I'm over-generalizing too early and we should just go with your initial suggestion.

**Comment by rhmdnd** [comment]
> > That's an interesting idea.
> > Would the process that ingests data take any additional key-value pairs outside the schema and attempt to insert them in this generic table? If so, would a client be able to fetch that information out using the gRPC API? I may have the cart in front of the horse, but I'm wondering how that will impact the perception of a public facing API. For example, if someone relies on fetching a non-standard key out the metadata, would we ever be able to standardize it as a first-class citizen?
> 
> The GRPC API can still be targetted and target a very specific implementation. The database (or model) doesn't need to be tied to the GRPC API.

Agreed. Were you anticipating a generic metadata gRPC attribute?

> 
> > My other thought here is about performance. The generic table would need to have specific data types (e.g., `TEXT`, `VARCHAR`). Should we stuff integers in as text-type and then convert them? In either case, I'm wondering what the performance implications would be if we handled the conversion in go, and/or didn't optimize the schema to build specific queries from the application
> 
> Definitely, this would have some performance impact. It really depends on the data ingestion rate. Maybe I'm over-generalizing too early and we should just go with your initial suggestion.

I think we can move schemas quickly and we're still in an exploratory phase (before we consolidate the schema). I certainly think we can add additional attributes or make changes as we start using this in development environments.

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Pull request merged**
